# Generated by Django 5.0.6 on 2026-07-11 20:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Primer nombre"),
                ),
                (
                    "second_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Segundo nombre"
                    ),
                ),
                (
                    "first_last_name",
                    models.CharField(max_length=100, verbose_name="Primer apellido"),
                ),
                (
                    "second_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Segundo apellido"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="Edad")),
                (
                    "height_cm",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Altura (cm)"
                    ),
                ),
                (
                    "current_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso actual (kg)",
                    ),
                ),
                (
                    "goal_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso meta (kg)",
                    ),
                ),
                (
                    "body_fat_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Calculado por el sistema a partir de medidas registradas por el coach.",
                        max_digits=4,
                        null=True,
                        verbose_name="% Grasa corporal",
                    ),
                ),
                (
                    "body_water_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Calculado por el sistema a partir de medidas registradas por el coach.",
                        max_digits=4,
                        null=True,
                        verbose_name="% Agua corporal",
                    ),
                ),
                (
                    "left_arm_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "right_arm_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "left_leg_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "right_leg_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "left_calf_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "right_calf_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "hip_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "back_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "chest_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "waist_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "fitness_goal",
                    models.CharField(
                        choices=[
                            ("GANAR_PESO", "Ganar peso"),
                            ("PERDER_PESO", "Perder peso"),
                            ("MANTENER_PESO", "Mantener peso"),
                            ("TONIFICAR", "Tonificar"),
                        ],
                        default="MANTENER_PESO",
                        max_length=20,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("SEDENTARIO", "Sedentario"),
                            ("MODERADO", "Moderado"),
                            ("ACTIVO", "Activo"),
                            ("MUY_ACTIVO", "Muy activo"),
                        ],
                        default="MODERADO",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "next_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Siguiente pago"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Pagado")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "informed_consent_signed",
                    models.BooleanField(
                        default=False, verbose_name="Consentimiento informado firmado"
                    ),
                ),
                (
                    "participates_in_study",
                    models.BooleanField(
                        default=True,
                        verbose_name="Participa en el estudio (oct-nov 2026)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Cuenta de autenticación ligada a este miembro (login en la app).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro",
                "verbose_name_plural": "Miembros",
                "ordering": ["first_name", "first_last_name"],
            },
        ),
    ]
