# Generated by Django 5.0.6 on 2026-07-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("HOMBRE", "Hombre"), ("MUJER", "Mujer")],
                help_text="Determina la rutina asignada del calendario semanal y la fórmula de % de grasa corporal usada.",
                max_length=10,
                null=True,
                verbose_name="Género",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="neck_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Requerido para calcular % de grasa corporal (U.S. Navy Method).",
                max_digits=5,
                null=True,
                verbose_name="Cuello (cm)",
            ),
        ),
    ]
