# Generated by Django 5.0.6 on 2026-07-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_correo_unico_y_dias_planificados"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="last_payment_date",
            field=models.DateField(
                blank=True,
                help_text="Se actualiza automáticamente al marcar 'Pagado'. Si es nulo, el miembro nunca ha sido marcado como pagado.",
                null=True,
                verbose_name="Último pago registrado",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="True mientras el usuario siga usando la contraseña temporal generada por el panel al darlo de alta.",
                verbose_name="Debe cambiar su contraseña",
            ),
        ),
    ]
