# Generated by Django 5.0.6 on 2026-09-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_member_last_payment_date_user_must_change_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="planned_nutrition_days",
            field=models.PositiveSmallIntegerField(
                help_text="Total de días de seguimiento nutricional que el coach planifica para el miembro durante el período de medición (actualmente un mes), no un valor semanal.",
                verbose_name="Días planificados de dieta",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="planned_training_days",
            field=models.PositiveSmallIntegerField(
                help_text="Total de sesiones de entrenamiento que el coach planifica para el miembro durante el período de medición (actualmente un mes), no un valor semanal.",
                verbose_name="Días planificados de rutina",
            ),
        ),
    ]
