# Generated by Django 5.0.6 on 2026-07-11 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PIERNA_CUADRICEPS", "Pierna - Cuádriceps"),
                            ("PECHO", "Pecho"),
                            ("BRAZOS_ESPALDA", "Brazos y Espalda"),
                            ("CARDIO", "Cardio"),
                            ("ABS", "ABS"),
                            ("PIERNA_GLUTEOS", "Pierna - Glúteos"),
                            ("HOMBRO", "Hombro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="exercise_icons/"
                    ),
                ),
                (
                    "reference_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="exercise_photos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ejercicio",
                "verbose_name_plural": "Ejercicios (catálogo predefinido)",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PIERNA_CUADRICEPS", "Pierna - Cuádriceps"),
                            ("PECHO", "Pecho"),
                            ("BRAZOS_ESPALDA", "Brazos y Espalda"),
                            ("CARDIO", "Cardio"),
                            ("ABS", "ABS"),
                            ("PIERNA_GLUTEOS", "Pierna - Glúteos"),
                            ("HOMBRO", "Hombro"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "estimated_duration_min_low",
                    models.PositiveSmallIntegerField(default=60),
                ),
                (
                    "estimated_duration_min_high",
                    models.PositiveSmallIntegerField(default=90),
                ),
                (
                    "estimated_calories",
                    models.PositiveSmallIntegerField(
                        default=400,
                        help_text="Calorías aproximadas quemadas al completar la rutina.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rutina",
                "verbose_name_plural": "Rutinas",
            },
        ),
        migrations.CreateModel(
            name="RoutineExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="routines.exercise",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="routines.routine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejercicio de rutina",
                "verbose_name_plural": "Ejercicios de rutina",
                "ordering": ["routine", "order"],
                "unique_together": {("routine", "exercise")},
            },
        ),
    ]
