# Generated by Django 5.0.6 on 2026-07-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledRoutineDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Día",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("HOMBRE", "Hombre"), ("MUJER", "Mujer")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PIERNA_CUADRICEPS", "Pierna - Cuádriceps"),
                            ("PECHO", "Pecho"),
                            ("BRAZOS_ESPALDA", "Brazos y Espalda"),
                            ("CARDIO", "Cardio"),
                            ("ABS", "ABS"),
                            ("PIERNA_GLUTEOS", "Pierna - Glúteos"),
                            ("HOMBRO", "Hombro"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Día de calendario semanal",
                "verbose_name_plural": "Calendario semanal de rutinas",
                "ordering": ["day_of_week", "gender"],
                "unique_together": {("day_of_week", "gender")},
            },
        ),
    ]
