# Generated by Django 5.0.6 on 2026-09-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0003_seed_weekly_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="category",
            field=models.CharField(
                choices=[
                    ("PIERNA_CUADRICEPS", "Pierna - Cuádriceps"),
                    ("PECHO", "Pecho"),
                    ("BRAZOS_ESPALDA", "Brazos y Espalda"),
                    ("CARDIO", "Workout"),
                    ("ABS", "ABS"),
                    ("PIERNA_GLUTEOS", "Pierna - Glúteos"),
                    ("HOMBRO", "Hombro"),
                    (
                        "PIERNA_CUADRICEPS_CIRCUITO",
                        "Pierna Cuádriceps + Circuito (Mujeres)",
                    ),
                    ("PECHO_HOMBRO_TRICEPS", "Pecho, Hombro y Tríceps (Mujeres)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="routine",
            name="category",
            field=models.CharField(
                choices=[
                    ("PIERNA_CUADRICEPS", "Pierna - Cuádriceps"),
                    ("PECHO", "Pecho"),
                    ("BRAZOS_ESPALDA", "Brazos y Espalda"),
                    ("CARDIO", "Workout"),
                    ("ABS", "ABS"),
                    ("PIERNA_GLUTEOS", "Pierna - Glúteos"),
                    ("HOMBRO", "Hombro"),
                    (
                        "PIERNA_CUADRICEPS_CIRCUITO",
                        "Pierna Cuádriceps + Circuito (Mujeres)",
                    ),
                    ("PECHO_HOMBRO_TRICEPS", "Pecho, Hombro y Tríceps (Mujeres)"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledroutineday",
            name="category",
            field=models.CharField(
                choices=[
                    ("PIERNA_CUADRICEPS", "Pierna - Cuádriceps"),
                    ("PECHO", "Pecho"),
                    ("BRAZOS_ESPALDA", "Brazos y Espalda"),
                    ("CARDIO", "Workout"),
                    ("ABS", "ABS"),
                    ("PIERNA_GLUTEOS", "Pierna - Glúteos"),
                    ("HOMBRO", "Hombro"),
                    (
                        "PIERNA_CUADRICEPS_CIRCUITO",
                        "Pierna Cuádriceps + Circuito (Mujeres)",
                    ),
                    ("PECHO_HOMBRO_TRICEPS", "Pecho, Hombro y Tríceps (Mujeres)"),
                ],
                max_length=30,
            ),
        ),
    ]
