# Generated by Django 5.0.6 on 2026-07-11 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("ml_predictions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pendiente de revisión"),
                            ("APPROVED", "Aprobada y en seguimiento"),
                            ("REJECTED", "Rechazada"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=20,
                    ),
                ),
                ("total_calories", models.PositiveSmallIntegerField()),
                ("protein_g", models.PositiveSmallIntegerField()),
                ("carbs_g", models.PositiveSmallIntegerField()),
                ("fats_g", models.PositiveSmallIntegerField()),
                ("generated_by_ml", models.BooleanField(default=False)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Solo un plan 'actual' por miembro a la vez.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to="members.member",
                    ),
                ),
                (
                    "ml_prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nutrition_plans",
                        to="ml_predictions.mlprediction",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan nutricional",
                "verbose_name_plural": "Planes nutricionales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MealSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("DESAYUNO", "Desayuno"),
                            ("REFACCION_I", "Refacción I"),
                            ("ALMUERZO", "Almuerzo"),
                            ("REFACCION_II", "Refacción II"),
                            ("CENA", "Cena"),
                        ],
                        max_length=20,
                    ),
                ),
                ("carbs_g", models.PositiveSmallIntegerField()),
                ("protein_g", models.PositiveSmallIntegerField()),
                ("fats_g", models.PositiveSmallIntegerField()),
                ("calories", models.PositiveSmallIntegerField()),
                ("suggestion_1", models.CharField(blank=True, max_length=255)),
                ("suggestion_2", models.CharField(blank=True, max_length=255)),
                ("suggestion_3", models.CharField(blank=True, max_length=255)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="nutrition.nutritionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sugerencia de comida",
                "verbose_name_plural": "Sugerencias de comida",
                "ordering": ["plan", "meal_time"],
            },
        ),
    ]
