# Generated by Django 5.0.6 on 2026-07-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionplan",
            name="ml_suggested_calories",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="ml_suggested_carbs_g",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="ml_suggested_fats_g",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nutritionplan",
            name="ml_suggested_protein_g",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="is_current",
            field=models.BooleanField(
                default=False,
                help_text="Solo un plan 'actual' por miembro a la vez — se activa al aprobar (ver NutritionPlanDetailView).",
            ),
        ),
    ]
