# Generated by Django 5.0.6 on 2026-07-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_nutritionplan_ml_suggested_calories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealsuggestion",
            options={
                "ordering": [
                    "plan",
                    models.Case(
                        models.When(meal_time="DESAYUNO", then=models.Value(0)),
                        models.When(meal_time="REFACCION_I", then=models.Value(1)),
                        models.When(meal_time="ALMUERZO", then=models.Value(2)),
                        models.When(meal_time="REFACCION_II", then=models.Value(3)),
                        models.When(meal_time="CENA", then=models.Value(4)),
                        output_field=models.IntegerField(),
                    ),
                ],
                "verbose_name": "Sugerencia de comida",
                "verbose_name_plural": "Sugerencias de comida",
            },
        ),
    ]
