# Generated by Django 5.0.6 on 2026-07-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_alter_mealsuggestion_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutritionplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_REVIEW", "Pendiente de revisión"),
                    ("APPROVED", "Aprobada y en seguimiento"),
                    ("REJECTED", "Rechazada"),
                    ("SUPERSEDED", "Reemplazada"),
                ],
                default="PENDING_REVIEW",
                max_length=20,
            ),
        ),
    ]
