# Generated by Django 5.0.6 on 2026-09-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0004_alter_nutritionplan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutritionplan",
            name="generated_by_ml",
            field=models.BooleanField(
                default=False,
                help_text="True si el plan se generó automáticamente por cálculo determinístico (Mifflin-St Jeor + multiplicador de actividad + reparto de macros por objetivo); False si lo creó una persona a mano. No implica que intervenga un modelo de aprendizaje automático — hoy no lo hay para nutrición.",
            ),
        ),
    ]
