# Generated by Django 5.0.6 on 2026-07-11 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("routines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyMeasurementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "body_fat_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "body_water_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_logs",
                        to="members.member",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de medidas corporales",
                "verbose_name_plural": "Registros de medidas corporales",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(verbose_name="Tiempo (minutos)"),
                ),
                (
                    "calories_burned",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Calorías quemadas según rutina y tiempo (métrica agregada en A3, reunión 2).",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to="members.member",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="routines.routine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de rutina completada",
                "verbose_name_plural": "Registros de rutinas completadas",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutExerciseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_weight_lb",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                (
                    "final_weight_lb",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                ("reps_completed", models.PositiveSmallIntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="routines.exercise",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_entries",
                        to="tracking.workoutsessionlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de ejercicio registrado",
                "verbose_name_plural": "Detalles de ejercicios registrados",
            },
        ),
        migrations.CreateModel(
            name="DailyNutritionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HECHO", "Hecho"),
                            ("PARCIALMENTE", "Parcialmente"),
                            ("SE_ME_FUE", "Se me fue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_logs",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro nutricional diario",
                "verbose_name_plural": "Registros nutricionales diarios",
                "ordering": ["-date"],
                "unique_together": {("member", "date")},
            },
        ),
    ]
